optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 200
  batch_size: 512
  save_model: true
  log_loss: false
  test_step: 1
  reproducible: true
  seed: 2023
  pretrain_path: "/home/asaliao/SSLRec/checkpoint/bert4rec/bert4rec-sports-1710580531.pth" #"/home/asaliao/SSLRec/checkpoint/bert4rec/bert4rec-reddit-1710574833.pth" #

test:
  metrics: [recall, ndcg, mrr]
  k: [5, 10, 20]
  batch_size: 512

data:
  type: sequential
  name: beauty #ml-20m

model:
  name: bert4rec
  dropout_rate: 0.1
  n_layers: 2
  embedding_size: 64
  mask_prob: 0.2
  n_heads: 2
  max_seq_len: 50

tune:
  enable: false
  hyperparameters: []
  layer_num: []
  reg_weight: []
